name: AnimatedPopups
main: AnimatedPopups\Main
version: 1.0
api: [2.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15]
author: jojoe77777
description: Send animated messages!
