text:
- 'You are playing on "put your server name here", have a good time {name}!!!'
- 'or make your message using these \ | / . , _ - )( ^ []{}`'
- 'example p.s delete all the messages you do not want'
- '|---/___/\-----------------/ \_\---.____________________.--|'
- '|----\  \ \---------------/  / /---|   _________________|--|'
- '|-----\  \ \-----___-----/  / /----|   |________.-----------|'             
- '|------\  \ \---/ _ \---/  / /-----|   _________|----------|'
- '|-------\  \ \./ /-\ \./  / /------|   |-------------------|'
- '|--------\  \   /---\ \  / /-------|   |-------------------|'
- '|---------\__\_/-----\__/_/--------|___|-------------------|'
interval: 1
random: false

offset-lines: 10
# 0 = loop, 1 = reverse loop
animation-type: 1
