text:
- '§1§l|§r§4§l§6§l-§4§l---------------------------------------------§1§l|§r'
- '§1§l|§r§4§l-§6§l-§4§l--------------------------------------------§1§l|§r'
- '§1§l|§r§4§l--§6§l-§4§l-------------------------------------------§1§l|§r'
- '§1§l|§r§4§l---§6§l-§4§l------------------------------------------§1§l|§r'
- '§1§l|§r§4§l----§6§l-§4§l-----------------------------------------§1§l|§r'
- '§1§l|§r§4§l-----§6§l-§4§l----------------------------------------§1§l|§r'
- '§1§l|§r§4§l------§6§l-§4§l---------------------------------------§1§l|§r'
- '§1§l|§r§4§l-------§6§l-§4§l--------------------------------------§1§l|§r'
- '§1§l|§r§4§l--------§6§l-§4§l-------------------------------------§1§l|§r'
- '§1§l|§r§4§l---------§6§l-§4§l------------------------------------§1§l|§r'
- '§1§l|§r§4§l----------§6§l-§4§l-----------------------------------§1§l|§r'
- '§1§l|§r§4§l-----------§6§l-§4§l----------------------------------§1§l|§r'
- '§1§l|§r§4§l------------§6§l-§4§l---------------------------------§1§l|§r'
- '§1§l|§r§4§l-------------§6§l-§4§l--------------------------------§1§l|§r'
- '§1§l|§r§4§l--------------§6§l-§4§l-------------------------------§1§l|§r'
- '§1§l|§r§4§l---------------§6§l-§4§l------------------------------§1§l|§r'
- '§1§l|§r§4§l----------------§6§l-§4§l-----------------------------§1§l|§r'
- '§1§l|§r§4§l-----------------§6§l-§4§l----------------------------§1§l|§r'
- '§1§l|§r§4§l------------------§6§l-§4§l---------------------------§1§l|§r'
- '§1§l|§r§4§l-------------------§6§l-§4§l--------------------------§1§l|§r'
- '§1§l|§r§4§l--------------------§6§l-§4§l-------------------------§1§l|§r'
- '§1§l|§r§4§l---------------------§6§l-§4§l------------------------§1§l|§r'
- '§1§l|§r§4§l----------------------§6§l-§4§l-----------------------§1§l|§r'
- '§1§l|§r§4§l-----------------------§6§l-§4§l----------------------§1§l|§r'
- '§1§l|§r§4§l------------------------§6§l-§4§l---------------------§1§l|§r'
- '§1§l|§r§4§l-------------------------§6§l-§4§l--------------------§1§l|§r'
- '§1§l|§r§4§l--------------------------§6§l-§4§l-------------------§1§l|§r'
- '§1§l|§r§4§l---------------------------§6§l-§4§l------------------§1§l|§r'
- '§1§l|§r§4§l----------------------------§6§l-§4§l-----------------§1§l|§r'
- '§1§l|§r§4§l-----------------------------§6§l-§4§l----------------§1§l|§r'
- '§1§l|§r§4§l------------------------------§6§l-§4§l---------------§1§l|§r'
- '§1§l|§r§4§l-------------------------------§6§l-§4§l--------------§1§l|§r'
- '§1§l|§r§4§l--------------------------------§6§l-§4§l-------------§1§l|§r'
- '§1§l|§r§4§l---------------------------------§6§l-§4§l------------§1§l|§r'
- '§1§l|§r§4§l----------------------------------§6§l-§4§l-----------§1§l|§r'
- '§1§l|§r§4§l-----------------------------------§6§l-§4§l----------§1§l|§r'
- '§1§l|§r§4§l------------------------------------§6§l-§4§l---------§1§l|§r'
- '§1§l|§r§4§l-------------------------------------§6§l-§4§l--------§1§l|§r'
- '§1§l|§r§4§l--------------------------------------§6§l-§4§l-------§1§l|§r'
- '§1§l|§r§4§l---------------------------------------§6§l-§4§l------§1§l|§r'
- '§1§l|§r§4§l----------------------------------------§6§l-§4§l-----§1§l|§r'
- '§1§l|§r§4§l-----------------------------------------§6§l-§4§l----§1§l|§r'
- '§1§l|§r§4§l------------------------------------------§6§l-§4§l---§1§l|§r'
- '§1§l|§r§4§l-------------------------------------------§6§l-§4§l--§1§l|§r'
- '§1§l|§r§4§l--------------------------------------------§6§l-§4§l-§1§l|§r'
- '§1§l|§r§4§l---------------------------------------------§6§l-§4§l§1§l|§r'

interval: 1
random: false

offset-lines: 10
# 0 = loop, 1 = reverse loop
animation-type: 1